CREATE TABLE IF NOT EXISTS "PRICES" (
    "ID" UUID PRIMARY KEY,
    "BRAND_ID" INTEGER NOT NULL,
    "PRODUCT_ID" INTEGER NOT NULL,
    "PRICE_LIST" INTEGER NOT NULL,
    "START_DATE" TIMESTAMP,
    "END_DATE" TIMESTAMP,
    "PRIORITY" INTEGER NOT NULL,
    "PRICE" NUMERIC(5,2) NOT NULL,
    "CURRENCY" VARCHAR(3) NOT NULL,
    UNIQUE("BRAND_ID", "PRODUCT_ID", "PRICE_LIST")
);