CREATE TABLE IF NOT EXISTS "PRICES" (
    "PRICE_LIST" INTEGER NOT NULL,
    "BRAND_ID" INTEGER NOT NULL,
    "PRODUCT_ID" INTEGER NOT NULL,
    "START_DATE" TIMESTAMP,
    "END_DATE" TIMESTAMP,
    "PRIORITY" INTEGER NOT NULL,
    "PRICE" NUMERIC(5,2) NOT NULL,
    "CURR" VARCHAR(3) NOT NULL
);